server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: localhost
      port: 8500
#      discovery:
#        service-name: ${spring.application.name}
#        prefer-ip-address: true
#        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
