server:
  port: 3344


spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fishool/springcloud-config.git
          # 指定查找目录
          search-paths:
            - spring-config
            - myorder
      label: master
#http://localhost:3344/master/config-dev.yml
  rabbitmq:
    host: 119.28.44.14
    port: 5672
    username: admin
    password: 851158220


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 暴露bus刷新配置的端点

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
