server:
  port: 8800 #端口
spring:
  application:
    name: operate-gateway-server #服务名称
  redis:
    host: localhost
    pool: 6379
    database: 0
  cloud: #配置SpringCloudGateway的路由
    nacos:
        discovery:
           server-addr: 127.0.0.1:8848 #注册中心地址
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: false

      routes:
        - id: javastudy       #唯一id
          uri: lb://javastudy #跳转服务
          predicates:         #匹配路径
            - Path=/javastudy/**
          filters:          # 跳转后 截掉path路径 前几位
            - StripPrefix=1